# Generated by Django 5.0.3 on 2024-04-27 08:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentorg', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orgmember',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='orgmember',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='orgmember',
            name='date_joined',
            field=models.DateField(default=datetime.date(2024, 4, 27)),
        ),
    ]
